// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_sgPoEucVYd_7dgzlx-Nj1kFxQmErWLc',
    appId: '1:426078226409:web:433ee65e91ba74b84c6d78',
    messagingSenderId: '426078226409',
    projectId: 'todo-b6b13',
    authDomain: 'todo-b6b13.firebaseapp.com',
    storageBucket: 'todo-b6b13.appspot.com',
    measurementId: 'G-6NTQ7H8E1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1eaVCVd9ymIzy0MCFOt1qxIayauty4AA',
    appId: '1:426078226409:android:622711f5a84f639a4c6d78',
    messagingSenderId: '426078226409',
    projectId: 'todo-b6b13',
    storageBucket: 'todo-b6b13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfDfwJ63DW5EyMpx6yNH3ZUEO2_ylOipQ',
    appId: '1:426078226409:ios:b9b3107e7023cdef4c6d78',
    messagingSenderId: '426078226409',
    projectId: 'todo-b6b13',
    storageBucket: 'todo-b6b13.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfDfwJ63DW5EyMpx6yNH3ZUEO2_ylOipQ',
    appId: '1:426078226409:ios:b9b3107e7023cdef4c6d78',
    messagingSenderId: '426078226409',
    projectId: 'todo-b6b13',
    storageBucket: 'todo-b6b13.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_sgPoEucVYd_7dgzlx-Nj1kFxQmErWLc',
    appId: '1:426078226409:web:bc14187392955b644c6d78',
    messagingSenderId: '426078226409',
    projectId: 'todo-b6b13',
    authDomain: 'todo-b6b13.firebaseapp.com',
    storageBucket: 'todo-b6b13.appspot.com',
    measurementId: 'G-W27FYSXCNK',
  );
}
